/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminContainer: typeof import('./../components/AdminContainer/index.vue')['default']
    ApiSelect: typeof import('./../components/ApiSelect/index.vue')['default']
    AppLink: typeof import('./../components/AppLink/index.vue')['default']
    Breadcrumb: typeof import('./../layouts/components/Breadcrumb/index.vue')['default']
    CheckboxGroup: typeof import('./../components/CheckboxGroup/index.vue')['default']
    CodeInput: typeof import('./../components/CodeInput/index.vue')['default']
    Content: typeof import('./../layouts/components/Content/index.vue')['default']
    DataTable: typeof import('./../components/DataTable/index.vue')['default']
    Footer: typeof import('./../layouts/components/Footer/index.vue')['default']
    Header: typeof import('./../layouts/components/Header/index.vue')['default']
    IconFont: typeof import('./../components/IconFont/index.vue')['default']
    IconPicker: typeof import('./../components/IconPicker/index.vue')['default']
    Logo: typeof import('./../layouts/components/Logo/index.vue')['default']
    Menu: typeof import('./../layouts/components/Menu/index.vue')['default']
    MenuForm: typeof import('./../views/menuManage/components/MenuForm.vue')['default']
    MenuItem: typeof import('./../layouts/components/Menu/MenuItem.vue')['default']
    MenuItemContent: typeof import('./../layouts/components/Menu/MenuItemContent.vue')['default']
    MenuTable: typeof import('./../views/menuManage/components/MenuTable.vue')['default']
    MenuTreeDrawer: typeof import('./../views/menuManage/components/MenuTreeDrawer.vue')['default']
    MenuTreeSelect: typeof import('./../views/menuManage/components/MenuTreeSelect.vue')['default']
    PasswordForm: typeof import('./../views/account/components/PasswordForm.vue')['default']
    ProfileForm: typeof import('./../views/account/components/ProfileForm.vue')['default']
    RadioGroup: typeof import('./../components/RadioGroup/index.vue')['default']
    RoleForm: typeof import('./../views/roleManage/components/RoleForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./../components/SearchForm/index.vue')['default']
    StatusText: typeof import('./../components/StatusText/index.vue')['default']
    TreeSelect: typeof import('./../components/TreeSelect/index.vue')['default']
    UserForm: typeof import('./../views/userManage/components/UserForm.vue')['default']
  }
}
